In [85]:
import numpy as np 
from numpy.linalg import inv

q = np.random.normal(0, 1, (4)) + \
    np.random.normal(0, 1, (4))*1j

n = np.linspace(0,10,4)

In [86]:
np.imag(np.exp(1j*(n)))

array([ 0.        , -0.19056796,  0.37415123, -0.54402111])

In [87]:
a = np.linspace(3, 3+4-1, 4)
len(a)
print(a)

[3. 4. 5. 6.]


In [88]:
np.imag(3+4j)

4.0

In [89]:
n_0 = 0
T = 1
N = 4

v1 = np.arange(n_0, n_0+N)
v2 = np.ones(N)

print(v1)
print(v2)
H = np.vstack([v1,v2]).T

a = np.array([1,1])

print(H)

print(H@a)

[0 1 2 3]
[1. 1. 1. 1.]
[[0. 1.]
 [1. 1.]
 [2. 1.]
 [3. 1.]]
[1. 2. 3. 4.]


In [90]:
m = np.array([[ 1, 1, 1],[ 0, 2, 5],[ 2, 5, -1]])
print(inv(m))

[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


In [91]:
C = np.cov(v1.reshape(-1,1).T,v1.reshape(-1,1).T)

print(C)

[[1.66666667 1.66666667]
 [1.66666667 1.66666667]]


In [92]:
avg = np.average(v1)
print(avg)

v = v1-avg 
vt = v.reshape(-1,1)

print(v)
print(vt)

cv = v * vt

print(cv)

1.5
[-1.5 -0.5  0.5  1.5]
[[-1.5]
 [-0.5]
 [ 0.5]
 [ 1.5]]
[[ 2.25  0.75 -0.75 -2.25]
 [ 0.75  0.25 -0.25 -0.75]
 [-0.75 -0.25  0.25  0.75]
 [-2.25 -0.75  0.75  2.25]]


In [98]:
x = np.array([1,2,3])
D = np.diag(x) + np.diag(x[:-1], 1)
print(D)

[[1 1 0]
 [0 2 2]
 [0 0 3]]


In [103]:
    x = np.ones(3)
    A = -np.diag(x) + np.diag(x[:-1], 1)
    C = A @ A.T
    print(inv(C))

[[1. 1. 1.]
 [1. 2. 2.]
 [1. 2. 3.]]


In [104]:
np.vstack(x)

array([[1.],
       [1.],
       [1.]])